# Site settings
title: PomDP the PhD Rapper
email: cgn@mit.edu
url: "https://www.phdrapper.com/"
description: "The official website of PomDP the PhD rapper."
baseurl: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Northcutt Labs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/thephdrapper/
  - title: facebook
    url: https://www.facebook.com/thephdrapper
  - title: twitter
    url: https://twitter.com/thephdrapper
 # - title: stack-overflow
 #  url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket
 #   url: http://bitbucket.org/jekyll
 # - title: github
 #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
